[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.deploy]
cmd = 'java -jar target/app-nuoc-mia-1.0.0.jar'

[start]
cmd = 'java -jar target/app-nuoc-mia-1.0.0.jar'
