# Nixpacks configuration for Railway
providers = ["java"]

[phases.setup]
nixPkgs = ['maven', 'jdk21']

[phases.build]
cmds = [
    'mvn clean package -DskipTests'
]

[phases.install]

[phases.start]
cmd = 'java -jar target/app-nuoc-mia-1.0.0.jar'

[start]
cmd = 'java -jar target/app-nuoc-mia-1.0.0.jar'

